name: Express App Build

run-name: Express App Production Container Build

on:
  push:
    branches: [ main ]

permissions:
  # id-token: write #
  contents: write

jobs:
  update:
    name: Update Express App Containers
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event to main."
      - run: echo "---HEAD COMMIT MESSAGE--"
      - run: echo "${{ github.event.head_commit.message }}"
      - run: echo "------------------------"

      - uses: actions/github-script@v7
        id: get_pr_data
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];
  
      - name: Pull Request data
        run: |
          echo '${{ fromJson(steps.get_pr_data.outputs.result).number }}'
          echo '${{ fromJson(steps.get_pr_data.outputs.result).title }}'

      - name: "Find Version from Commit Message"
        id: findVersion
        shell: pwsh
        run: |
          $commitMsg = "${{ github.event.head_commit.message }}"
          $version = [regex]::matches($commitMsg, '(?<=\[version:).*(?=])').value
          $major = $commitMsg -match '(?<=\[)major(?=])'
          $minor = $commitMsg -match '(?<=\[)minor(?=])'
          $build = $commitMsg -match '(?<=\[)build(?=])'

          Write-Host "Version found in commit message: $version"
          Write-Host "Bump Major: $major"
          Write-Host "Bump Minor: $minor"
          Write-Host "Bump Build: $build"

          Write-Output "targetVersion=$version" >> $Env:GITHUB_OUTPUT
          Write-Output "bumpMajor=$major" >> $Env:GITHUB_OUTPUT
          Write-Output "bumpMinor=$minor" >> $Env:GITHUB_OUTPUT
          Write-Output "bumpBuild=$build" >> $Env:GITHUB_OUTPUT

      - name: "Test Version from Commit Message"
        id: testVersion
        shell: pwsh
        run: |
          $targetVersion = "${{ steps.findVersion.outputs.targetVersion }}"
          $bumpMajor = [System.Convert]::ToBoolean("${{ steps.findVersion.outputs.bumpMajor }}")
          $bumpMinor = [System.Convert]::ToBoolean("${{ steps.findVersion.outputs.bumpMinor }}")
          $bumpBuild = [System.Convert]::ToBoolean("${{ steps.findVersion.outputs.bumpBuild }}")

          Write-Host "Version passed in: $targetVersion"
          Write-Host "Bump Major passed: $bumpMajor"
          Write-Host "Bump Minor passed: $bumpMinor"
          Write-Host "Bump Build passed: $bumpBuild"

      - name: Checkout Express App Code
        uses: actions/checkout@v4

      - name: "Increment Express App Version"
        id: updateVersion
        shell: pwsh
        run: |
          $packageJson = Get-Content -Path .\package.json | ConvertFrom-Json
          $packageJsonVer = [System.Version]$packageJson.version
          # $newVersion = "{0}.{1}.{2}" -f ($packageJsonVer.Major + 1), $packageJsonVer.Minor, $packageJsonVer.Build
          # $newVersion = "{0}.{1}.{2}" -f $packageJsonVer.Major, ($packageJsonVer.Minor + 1), $packageJsonVer.Build
          $newVersion = "{0}.{1}.{2}" -f $packageJsonVer.Major, $packageJsonVer.Minor, ($packageJsonVer.Build + 1)
          $packageJson.version = $newVersion
          $packageJson | ConvertTo-Json | Set-Content -Path .\package.json

          Write-Output "ipamVersion=$newVersion" >> $Env:GITHUB_OUTPUT

      - name: "Create Express App ZIP Asset"
        id: createZipAsset
        shell: pwsh
        run: |
          Compress-Archive -Path .\app.js -DestinationPath .\assets\express.zip -Force

      - name: Checkin Updated Express Code
        id: checkinCode
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "expressactions@users.noreply.github.com"
          git commit -a -m "Updated Express App Version"
          git push

      # - name: "Publish Express App Release"
      #   id: publishRelease
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: v${{ steps.updateVersion.outputs.ipamVersion }}
      #     release_name: Release v${{ steps.updateVersion.outputs.ipamVersion }}
      #     body: |
      #       Express App Release
      #     draft: false
      #     prerelease: false

      - name: Publish Express App Release Asset
        id: publishRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.updateVersion.outputs.ipamVersion }}
          release_name: Release v${{ steps.updateVersion.outputs.ipamVersion }}
        run: |
          gh release create "$tag_name" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$release_name" \
            --notes "Express App Release"

      # - name: Upload Express App Release Asset
      #   id: uploadReleaseAsset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.publishRelease.outputs.upload_url }}
      #     asset_path: ./assets/express.zip
      #     asset_name: express.zip
      #     asset_content_type: application/zip

      - name: Publish Express App Release Asset
        id: uploadReleaseAsset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.updateVersion.outputs.ipamVersion }}
          asset_path: ./assets/express.zip
        run: |
          gh release upload "$tag_name" "$asset_path"
