name: Express App Build

run-name: Express App Production Container Build

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  update:
    name: Update Express App Containers
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event to main."

      - name: Checkout Express App Code
        uses: actions/checkout@v3

      - name: "Increment Express App Version"
        id: updateVersion
        shell: pwsh
        run: |
          $packageJson = Get-Content -Path .\package.json | ConvertFrom-Json
          $packageJsonVer = [System.Version]$packageJson.version
          $packageJson.version = "{0}.{1}.{2}" -f ($packageJsonVer.Major + 1), $packageJsonVer.Minor, $packageJsonVer.Build
          $packageJson | ConvertTo-Json | Set-Content -Path .\package.json

          Write-Output "ipamVersion=$newVersion" >> $Env:GITHUB_OUTPUT

      - name: Checkin Updated Express Code
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "expressactions@users.noreply.github.com"
          git commit -a -m "Updated Express App Version"
          git push
