name: Express App Release

run-name: Create Express App Release

on:
  push:
    tags: [ 'v*.*.*' ]

permissions:
  contents: write

jobs:
  release:
    name: Create Express App Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Express App Code
        uses: actions/checkout@v4

      - name: Create Express App Release
        id: publishRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tagName: v${{ github.ref_name }}
        run: |
          gh release create "$tagName" \
            --repo="$GITHUB_REPOSITORY" \
            --title="$tagName" \
            --notes "Express App Release"

      - name: Publish Express App Release Asset
        id: uploadReleaseAsset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tagName: v${{ github.ref_name }}
          assetPath: ./assets/express.zip
        run: |
          gh release upload "$tagName" "$assetPath"
