name: Express App Testing

run-name: Express App Deployment & Testing

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'

jobs:
  deploy:
    name: Test Express App
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        shell: pwsh
        run: |
          Write-Host "Hello!"
