name: Express App Testing

run-name: Express App Production Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy Express App
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        shell: pwsh
        run: |
          Write-Host "Hello!"
