name: Express App Versioning

run-name: Express App Version Update

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  version:
    name: Update Express App Version
    runs-on: ubuntu-latest
    outputs:
      ipamVersion: ${{ steps.updateVersion.outputs.ipamVersion }}
      prNumber: ${{ steps.prData.outputs.prNumber }}
    steps:
      - run: echo "Job triggered by a ${{ github.event_name }} event to main."
      - run: echo "---HEAD COMMIT MESSAGE--"
      - run: echo "${{ github.event.head_commit.message }}"
      - run: echo "------------------------"

      - uses: actions/github-script@v7
        id: getPullRequestData
        with:
          script: |
            return (
              await github.rest.repos.listPullRequestsAssociatedWithCommit({
                commit_sha: context.sha,
                owner: context.repo.owner,
                repo: context.repo.repo,
              })
            ).data[0];

      - name: Pull Request Data
        id: prData
        run: |
          echo '${{ fromJson(steps.getPullRequestData.outputs.result).title }}'
          echo '${{ fromJson(steps.getPullRequestData.outputs.result).body }}'
          echo '${{ fromJson(steps.getPullRequestData.outputs.result).number }}'
          echo "prNumber=${{ fromJson(steps.getPullRequestData.outputs.result).number }}" >> $GITHUB_OUTPUT

      - name: Checkout Express App Code
        uses: actions/checkout@v4

      - name: Configure Git
        id: configureGit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "expressactions@users.noreply.github.com"

      - name: Create Temporary Branch
        id: createBranch
        env:
          prNumber: ${{ steps.prData.outputs.prNumber }}
        run: |
          git checkout -b "express-version-$prNumber"
          git push origin "express-version-$prNumber"

      - name: "Update Express App Version"
        id: updateVersion
        env:
          prBody: ${{ fromJson(steps.getPullRequestData.outputs.result).body }}
        shell: pwsh
        run: |
          $version = [regex]::matches($env:prBody, '(?<=\[version:).*(?=])').value
          $major = $env:prBody -match '(?<=\[)major(?=])'
          $minor = $env:prBody -match '(?<=\[)minor(?=])'
          $build = $env:prBody -match '(?<=\[)build(?=])'

          $packageJson = Get-Content -Path .\package.json | ConvertFrom-Json
          $packageJsonVer = [System.Version]$packageJson.version

          Write-Host "Current package.json version: $packageJsonVer"
          Write-Host "Version found in commit message: $version"
          Write-Host "Bump Major: $major"
          Write-Host "Bump Minor: $minor"
          Write-Host "Bump Build: $build"

          try {
            $version = [System.Version]$version
            $newVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build
          } catch {
            $version = $null
          }

          if ($version) {
            Write-Host "Version specificed"
            $targetVersion = $newVersion
          } elseif ($major) {
            Write-Host "Major detected"
            $targetVersion = "{0}.0.0" -f ($packageJsonVer.Major + 1)
          } elseif ($minor) {
            Write-Host "Minor detected"
            $targetVersion = "{0}.{1}.0" -f $packageJsonVer.Major, ($packageJsonVer.Minor + 1)
          } else {
            Write-Host "Build detected"
            $targetVersion = "{0}.{1}.{2}" -f $packageJsonVer.Major, $packageJsonVer.Minor, ($packageJsonVer.Build + 1)
          }

          Write-Host "Target version: $targetVersion"

          $packageJson.version = $targetVersion
          $packageJson | ConvertTo-Json | Set-Content -Path .\package.json

          Write-Output "ipamVersion=$targetVersion" >> $Env:GITHUB_OUTPUT

      - name: "Create Express App ZIP Asset"
        id: createZipAsset
        shell: pwsh
        run: |
          Compress-Archive -Path .\package.json -DestinationPath .\assets\express.zip -Force

      - name: Checkin Updated Express App Code
        id: checkinCode
        env:
          prNumber: ${{ steps.prData.outputs.prNumber }}
        run: |
          git commit -a -m "Updated Express App Version and Created Release Asset"
          git push origin "express-version-$prNumber"

      - name: Create and Merge Pull Request
        id: pullRequest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          prNumber: ${{ steps.prData.outputs.prNumber }}
        run: |
          git checkout main
          gh pr create --base main --head "express-version-$prNumber" --title "Update Express App Version" --body "-Updated Version to v$prNumber"
          gh pr merge "express-version-$prNumber" -t "Merge pull request from DCMattyG/express-version-$prNumber [skip ci]" -m
          git pull

      - name: Delete Temporary Branch
        id: deleteBranch
        env:
          prNumber: ${{ steps.prData.outputs.prNumber }}
        run: |
          git push origin --delete "express-version-$prNumber"

      - name: Tag Main Branch
        id: tagBranch
        env:
          tagName: v${{ steps.updateVersion.outputs.ipamVersion }}
        run: |
          git tag $tagName
          git push origin --tags
